version: '2'
services:
  jenkins:
    build: ./master
    image: bizeps/jenkins
    container_name: bizJenkins
    ports:
      - "8080:8080"
    volumes:
      - bizJenkinsHome:/var/jenkins_home
      - /var/certs/docker/client:/var/certs/docker/localDockerHost:ro
  
  jenkinsUser:
    build: ./user
    image: bizeps/jenkinsuser

volumes:
  bizJenkinsHome
