version: '2'
services:
  jenkins:
    build: ./master
    image: bizeps/jenkins:2.121.1-r3
    container_name: bizJenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - bizJenkinsHome:/var/jenkins_home

volumes:
  bizJenkinsHome:
